export const FORGE_FIELD_MODULE_REF = Symbol('FORGE_FIELD_MODULE_REF');
export const FORGE_TOKEN_ROOT_MODULE = Symbol('FORGE_TOKEN_ROOT_MODULE');

export const FORGE_PATCHED = Symbol('FORGE_PATCHED');
export const FORGE_PATCH_BOOT_CALLBACK = Symbol('FORGE_PATCH_BOOT_CALLBACK');
export const FORGE_PATCH_ENABLE_INIT = Symbol('FORGE_PATCH_ENABLE_INIT');
